// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// prodCpp
Eigen::MatrixXd prodCpp(const Eigen::Map<Eigen::MatrixXd>& B, const Eigen::Map<Eigen::MatrixXd>& C);
RcppExport SEXP SmartSVA_prodCpp(SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type C(CSEXP);
    __result = Rcpp::wrap(prodCpp(B, C));
    return __result;
END_RCPP
}
// crossprodCpp
Eigen::MatrixXd crossprodCpp(const Eigen::Map<Eigen::MatrixXd>& A);
RcppExport SEXP SmartSVA_crossprodCpp(SEXP ASEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type A(ASEXP);
    __result = Rcpp::wrap(crossprodCpp(A));
    return __result;
END_RCPP
}
// tcrossprodCpp
Eigen::MatrixXd tcrossprodCpp(const Eigen::Map<Eigen::MatrixXd>& B, const Eigen::Map<Eigen::MatrixXd>& C);
RcppExport SEXP SmartSVA_tcrossprodCpp(SEXP BSEXP, SEXP CSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type B(BSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd>& >::type C(CSEXP);
    __result = Rcpp::wrap(tcrossprodCpp(B, C));
    return __result;
END_RCPP
}
