# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

prodCpp <- function(B, C) {
    .Call('SmartSVA_prodCpp', PACKAGE = 'SmartSVA', B, C)
}

crossprodCpp <- function(A) {
    .Call('SmartSVA_crossprodCpp', PACKAGE = 'SmartSVA', A)
}

tcrossprodCpp <- function(B, C) {
    .Call('SmartSVA_tcrossprodCpp', PACKAGE = 'SmartSVA', B, C)
}

